<a href="https://colab.research.google.com/github/VindaShinde/DonorBrain/blob/master/First_Python_notebook_Basic3_numpy_panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy and Pandas

In [ ]:
import numpy as np

In [ ]:
arr_1 = np.array([0,1,2,3]) #np object calls function array and defines one dimentional array
print(arr_1)
arr_2 = np.array([[0,3,5],[2,8,7]]) # 2D array
arr_2

[0 1 2 3]


array([[0, 3, 5],
       [2, 8, 7]])

In [ ]:
print(arr_2.shape) #To find shape
arr_2.ndim #To find dimention

(2, 3)


2

In [ ]:
#To generate and array of size 12...
arr_3 = np.arange(12) #This can also be creted as (0,12)
print(arr_3)

arr_4 = np.arange(2,14,2) #From 2 till 14 at the gap of 2 steps
print(arr_4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 2  4  6  8 10 12]


### $ndarray.linspace$ generates linear evenly spaced elements between the start and the end

In [ ]:
  arr_5 = np.linspace(0,2,16) #generate 0 to 2 values in 16 values
  arr_5

array([0.        , 0.13333333, 0.26666667, 0.4       , 0.53333333,
       0.66666667, 0.8       , 0.93333333, 1.06666667, 1.2       ,
       1.33333333, 1.46666667, 1.6       , 1.73333333, 1.86666667,
       2.        ])

In [ ]:
print(np.zeros((2,3,4)))# 2 outer rows, and 3X4 array within - filled with 0 values
np.ones((2,3,4)) #filled with 1 values

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#create diagonal array
np.diag((3,4,5,7)) #takes array as parameter 

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

# Random numbers generation
produces uniformly distributed random numbers with range 0 to n(upper limit)

In [ ]:
np.random.seed(200) #set seed
arr_6 = np.random.rand(3)
print(arr_6)

arr_7 = np.random.rand(5)
arr_7

[0.94763226 0.22654742 0.59442014]


array([0.42830868, 0.76414069, 0.00286059, 0.35742368, 0.90969489])

In [ ]:
# empty - Using np.empty to create an uninitialized array is a cheaper and faster way to allocate an array,
# However, you should only use it if you're sure that all the elements will be initialized later:
np.empty((2,2))

array([[1.5e-323, 2.0e-323],
       [2.5e-323, 3.5e-323]])

In [ ]:
#The np.tile function allows one to construct an array from a smaller array by repeating it several times on the basis of a parameter:
arr_8 = np.array([[1,2],[6,7]],dtype='float') #define array data type
print(np.tile(np.array(arr_8),3))
print(np.tile(np.array(arr_8),(3,3)))
arr_8.dtype

[[1. 2. 1. 2. 1. 2.]
 [6. 7. 6. 7. 6. 7.]]
[[1. 2. 1. 2. 1. 2.]
 [6. 7. 6. 7. 6. 7.]
 [1. 2. 1. 2. 1. 2.]
 [6. 7. 6. 7. 6. 7.]
 [1. 2. 1. 2. 1. 2.]
 [6. 7. 6. 7. 6. 7.]]


dtype('float64')

In [ ]:
sar=np.array(['Goodbye','Welcome','Tata','Goodnight']); print(sar.dtype); print(sar)
# we cannot create variable-length strings in NumPy, since NumPy needs to know how much space to allocate for the string.


<U9
['Goodbye' 'Welcome' 'Tata' 'Goodnight']


In [ ]:
# change data type of array
r_arr = np.array([5,2.3,8,9.7]); r_arr
type(r_arr)
r_arr1 = np.array([5,3,8,7])

print(r_arr.astype(int)) #from float to int
r_arr1.astype(float)

[5 2 8 9]


array([5., 3., 8., 7.])

# Slicing and indexing

Indexing

In [ ]:
ar = np.arange(5); print (ar); ar[0], ar[1], ar[-1::],ar[::-1]#reverse array order
ar[-2] = 7; ar

[0 1 2 3 4]


array([0, 1, 2, 7, 4])

In [ ]:
#Multi-dimensional arrays are indexed using tuples of integers:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); print(ar)
ar[1,2]#as index is from 0, it shows 2nd row and 3rd column

[[ 2  3  4]
 [ 9  8  7]
 [11 12 13]]


7

In [ ]:
#set specific value in array
ar [1,2]= 5; ar

array([[ 2,  3,  4],
       [ 9,  8,  5],
       [11, 12, 13]])

In [ ]:
print("1:",ar[1:]) #retrive all rows from 1
print("2:",ar[1]) #retrrive single row of index 1
print("3:",ar[0:2]) #from 0 to 2 and do not take last

print("4:",ar[:,1]) #retrives cloumn indexed 1 and starting ':' shows all rows
print("5:",ar[:,-1])# last column
print("6:",ar[:,1:]) #from indexd 1 to all columns

print("7:",ar[1:,1])

###'''Thus, for 2D arrays, the first dimension denotes rows and the second dimension, the columns. 
### The colon (:) denotes selection across all elements of the dimension.'''


1: [[ 9  8  5]
 [11 12 13]]
2: [9 8 5]
3: [[2 3 4]
 [9 8 5]]
4: [ 3  8 12]
5: [ 4  5 13]
6: [[ 3  4]
 [ 8  5]
 [12 13]]
7: [ 8 12]


## Array slicing
Arrays can be sliced using the following syntax: ar[startIndex: endIndex: stepValue].

In [ ]:
ar = 3*np.arange(2,20,2); print("Original array:",ar)
print(ar[1:6:2])
#if we wish to include the endIndex value, we need to go above it, as follows:
print(ar[1:9])
print(ar[:4]) # print from 0 to 3
print(ar[::4]) #step value is 4

Original array: [ 6 12 18 24 30 36 42 48 54]
[12 24 36]
[12 18 24 30 36 42 48 54]
[ 6 12 18 24]
[ 6 30 54]
